# Generated by Django 4.1.7 on 2023-05-03 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_alter_post_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['sequence', '-created_on']},
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replier_name', models.CharField(default='', max_length=100)),
                ('reply_content', models.TextField()),
                ('replied_date', models.DateTimeField(auto_now_add=True)),
                ('reply_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_blog.comment')),
            ],
        ),
    ]
