# Generated by Django 4.1.7 on 2023-05-03 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0010_alter_post_options_replycomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
