# Generated by Django 4.1.7 on 2023-05-11 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0021_alter_postfile_post_alter_replycomment_reply_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ccomment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.comment'),
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
