# Generated by Django 4.1.7 on 2023-05-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0022_comment_ccomment_date_comment_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ccomment_date',
            new_name='comment_date',
        ),
    ]
