# Generated by Django 4.1.7 on 2023-05-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_blog", "0023_rename_ccomment_date_comment_comment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
    ]
